modLoader="javafml"
loaderVersion="*"
issueTrackerURL="https://github.com/CipherXOR/ModernOculus/issues"
license="LGPL-3.0-only"

[[mods]]
modId="oculus"
version="${version}"
displayURL = "https://github.com/CipherXOR/ModernOculus"
displayName="ModernOculus"
logoFile="oculus-logo.png"
authors="CipherXOR, NanoLive, dima_dencep, coderbot, IMS212, Justsnoopy30, FoundationGames"
description='''
ModernOculus is a community fork of Oculus, which is an unofficial Forge port of Iris Shaders.
'''
provides = ["iris"]
side = "CLIENT"

[[mixins]]
config="mixins.oculus.json"

[[mixins]]
config="mixins.oculus.fantastic.json"

[[mixins]]
config="mixins.oculus.vertexformat.json"

[[mixins]]
config="mixins.oculus.bettermipmaps.json"

[[mixins]]
config="mixins.oculus.fixes.maxfpscrash.json"

[[mixins]]
config="oculus-batched-entity-rendering.mixins.json"

[[mixins]]
config="mixins.oculus.compat.sodium.json"

[[mixins]]
config="mixins.oculus.compat.indigo.json"

[[mixins]]
config="mixins.oculus.compat.indium.json"

[[mixins]]
config="mixins.oculus.compat.dh.json"

[[mixins]]
config="mixins.oculus.compat.pixelmon.json"

[mods."sodium:options"]
"mixin.features.render.world.sky"=false
"mixin.features.render.entity"=false
"mixin.features.render.gui.font"=false
"mixin.features.render.gui.debug"=false

[[dependencies.oculus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.oculus]]
modId = "embeddium"
mandatory = false
versionRange = "[0.3.1,)"
ordering = "NONE"
side = "CLIENT"